apiVersion: v1
kind: Secret
metadata:
  name: homechart
  labels:
    {{- include "homechart.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $k, $v := .Values.homechart.config.secrets }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
{{- if .Values.postgresql.enabled }}
  HOMECHART_postgresql_database: {{ .Values.postgresql.config.username | b64enc | quote }}
  HOMECHART_postgresql_password: {{ .Values.postgresql.config.password | b64enc | quote }}
  HOMECHART_postgresql_username: {{ .Values.postgresql.config.username | b64enc | quote }}
{{- end }}
