{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    {{- include "homechart.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgresql.config.password | b64enc | quote }}
  username: {{ .Values.postgresql.config.username | b64enc | quote }}
{{- end }}
