apiVersion: v1
kind: Service
metadata:
  name: homechart
  labels:
    {{- include "homechart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: homechart
    service: homechart
