apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    {{- include "homechart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app: homechart
    service: postgresql
